import os
import sys
from datetime import datetime, timedelta


# =========================================================
# PROJECT PATH SETUP
# =========================================================

CURRENT_DIR = os.path.dirname(
    os.path.abspath(__file__)
)

PROJECT_ROOT = os.path.dirname(
    CURRENT_DIR
)

HONEYPOT_DIR = os.path.join(
    PROJECT_ROOT,
    "honeypot"
)

TRAFFIC_ISOLATION_DIR = os.path.join(
    PROJECT_ROOT,
    "traffic-isolation"
)

PACKET_MONITORING_DIR = os.path.join(
    PROJECT_ROOT,
    "packet-monitoring"
)


for path in [
    CURRENT_DIR,
    HONEYPOT_DIR,
    TRAFFIC_ISOLATION_DIR,
    PACKET_MONITORING_DIR
]:

    if path not in sys.path:

        sys.path.insert(
            0,
            path
        )


# =========================================================
# IMPORT EXISTING MODULES
# =========================================================

from isolation_manager import IsolationManager
from response_logger import ResponseLogger
from honeypot import HoneypotManager
from traffic_isolation import TrafficIsolationEngine
from database import get_detections_by_source_ip


# =========================================================
# SELF-HEALING MANAGER
# =========================================================

class SelfHealingManager:

    def __init__(self):

        self.isolation_manager = (
            IsolationManager()
        )

        self.traffic_isolation = (
            TrafficIsolationEngine()
        )

        self.honeypot_manager = (
            HoneypotManager()
        )

        self.response_logger = (
            ResponseLogger()
        )


    # =====================================================
    # GET RECENT SECURITY EVENTS
    # =====================================================

    def get_recent_events(
        self,
        source_ip,
        minutes=5
    ):

        """
        Get security events generated by a device
        during the recent monitoring window.

        Old historical attacks should not permanently
        prevent recovery.
        """

        all_events = (
            get_detections_by_source_ip(
                source_ip
            )
        )

        cutoff_time = (
            datetime.now()
            -
            timedelta(
                minutes=minutes
            )
        )

        recent_events = []


        for event in all_events:

            timestamp = event.get(
                "timestamp"
            )

            if not timestamp:

                continue


            try:

                event_time = (
                    datetime.fromisoformat(
                        timestamp
                    )
                )

            except ValueError:

                continue


            if event_time >= cutoff_time:

                recent_events.append(
                    event
                )


        return recent_events


    # =====================================================
    # CHECK FOR RECENT MALICIOUS ACTIVITY
    # =====================================================

    def has_recent_threat(
        self,
        source_ip,
        minutes=5
    ):

        """
        Returns True if the device generated a
        malicious security event recently.
        """

        recent_events = (
            self.get_recent_events(
                source_ip,
                minutes
            )
        )


        malicious_types = [

            "POSSIBLE_PHISHING",

            "POSSIBLE_DNS_SPOOFING",

            "POSSIBLE_ARP_SPOOFING"
        ]


        for event in recent_events:

            attack_type = event.get(
                "attack_type"
            )

            if attack_type in malicious_types:

                return True


        return False


    # =====================================================
    # THREAT CLEARANCE CHECK
    # =====================================================

    def check_threat_clearance(
        self,
        source_ip,
        trust_score,
        behavior_risk,
        monitoring_minutes=5
    ):

        """
        Determine whether a device is safe enough
        to begin recovery.

        Conditions:

        1. No recent malicious activity.
        2. Trust score is high enough.
        3. Behavior risk is below critical level.

        NOTE:
        Behavior risk is supplied by the current
        Zero Trust evaluation. Recent events are
        checked separately so old attacks do not
        permanently prevent recovery.
        """

        recent_events = (
            self.get_recent_events(
                source_ip,
                monitoring_minutes
            )
        )


        recent_threat = (
            self.has_recent_threat(
                source_ip,
                monitoring_minutes
            )
        )


        trust_safe = (
            trust_score >= 80
        )


        behavior_safe = (
            behavior_risk < 70
        )


        threat_cleared = (

            not recent_threat

            and trust_safe

            and behavior_safe
        )


        return {

            "source_ip": source_ip,

            "recent_events":
                len(recent_events),

            "recent_threat":
                recent_threat,

            "trust_score":
                trust_score,

            "trust_safe":
                trust_safe,

            "behavior_risk":
                behavior_risk,

            "behavior_safe":
                behavior_safe,

            "threat_cleared":
                threat_cleared
        }


    # =====================================================
    # CAN RECOVER
    # =====================================================

    def can_recover(
        self,
        source_ip,
        trust_score,
        behavior_risk,
        monitoring_minutes=5
    ):

        result = (
            self.check_threat_clearance(
                source_ip,
                trust_score,
                behavior_risk,
                monitoring_minutes
            )
        )


        return result


    # =====================================================
    # RECOVER DEVICE
    # =====================================================

    def recover_device(
        self,
        source_ip,
        trust_score,
        behavior_risk,
        reason="Threat cleared"
    ):

        timestamp = (
            datetime.now().isoformat()
        )


        print(
            "\n"
            + "=" * 60
        )

        print(
            "              SELF-HEALING PROCESS"
        )

        print(
            "=" * 60
        )


        print(
            f"\nDevice IP       : "
            f"{source_ip}"
        )

        print(
            f"Trust Score     : "
            f"{trust_score}"
        )

        print(
            f"Behavior Risk   : "
            f"{behavior_risk}"
        )

        print(
            f"Recovery Reason : "
            f"{reason}"
        )


        # -------------------------------------------------
        # CHECK THREAT CLEARANCE
        # -------------------------------------------------

        print(
            "\n[1] Checking recent threat activity..."
        )


        clearance = (
            self.check_threat_clearance(
                source_ip,
                trust_score,
                behavior_risk
            )
        )


        print(
            f"Recent Events   : "
            f"{clearance['recent_events']}"
        )

        print(
            f"Recent Threat   : "
            f"{clearance['recent_threat']}"
        )

        print(
            f"Trust Safe      : "
            f"{clearance['trust_safe']}"
        )

        print(
            f"Behavior Safe   : "
            f"{clearance['behavior_safe']}"
        )


        # -------------------------------------------------
        # RECOVERY DENIED
        # -------------------------------------------------

        if not clearance["threat_cleared"]:

            print(
                "\n[!] THREAT NOT CLEARED"
            )

            print(
                "[!] Device remains protected."
            )


            return {

                "source_ip":
                    source_ip,

                "action":
                    "RECOVER",

                "status":
                    "DENIED",

                "clearance":
                    clearance,

                "message":
                    "Threat conditions are still present"
            }


        print(
            "\n[+] THREAT CLEARED"
        )

        print(
            "[+] Recovery conditions satisfied."
        )


        # -------------------------------------------------
        # RELEASE ISOLATION
        # -------------------------------------------------

        print(
            "\n[2] Releasing device isolation..."
        )


        isolation_result = (
            self.isolation_manager.release_device(
                source_ip,
                reason=reason
            )
        )


        print(
            isolation_result
        )


        # -------------------------------------------------
        # REMOVE TRAFFIC BLOCK
        # -------------------------------------------------

        print(
            "\n[3] Removing traffic isolation..."
        )


        traffic_result = (
            self.traffic_isolation.release_device(
                source_ip,
                reason=reason
            )
        )


        print(
            traffic_result
        )


        # -------------------------------------------------
        # STOP HONEYPOT
        # -------------------------------------------------

        print(
            "\n[4] Stopping honeypot..."
        )


        honeypot_result = (
            self.honeypot_manager.stop_honeypot(
                source_ip,
                reason=reason
            )
        )


        print(
            honeypot_result
        )


        # -------------------------------------------------
        # VERIFY
        # -------------------------------------------------

        print(
            "\n[5] Verifying normal network access..."
        )


        traffic_status = (
            self.traffic_isolation.check_traffic(
                source_ip
            )
        )


        isolation_status = (
            self.isolation_manager.check_access(
                source_ip
            )
        )


        honeypot_active = (
            self.honeypot_manager.is_deployed(
                source_ip
            )
        )


        print(
            f"Traffic Status  : "
            f"{traffic_status}"
        )

        print(
            f"Access Status   : "
            f"{isolation_status}"
        )

        print(
            f"Honeypot Active : "
            f"{honeypot_active}"
        )


        # -------------------------------------------------
        # COMPLETE RECOVERY
        # -------------------------------------------------

        recovery_success = (

            not self.isolation_manager.is_isolated(
                source_ip
            )

            and

            not self.traffic_isolation.is_blocked(
                source_ip
            )

            and

            not honeypot_active
        )


        if recovery_success:

            print(
                "\n[6] SELF-HEALING SUCCESSFUL"
            )

            print(
                "[+] Device returned to normal access."
            )


            self.response_logger.log_response(

                source_ip=source_ip,

                action="RECOVER",

                status="RECOVERED",

                trust_score=trust_score,

                behavior_risk=behavior_risk,

                reason=reason,

                message=(
                    "Device successfully recovered "
                    "after threat clearance"
                )
            )


            return {

                "source_ip":
                    source_ip,

                "action":
                    "RECOVER",

                "status":
                    "RECOVERED",

                "trust_score":
                    trust_score,

                "behavior_risk":
                    behavior_risk,

                "traffic_status":
                    "ALLOWED",

                "isolation_status":
                    "RELEASED",

                "honeypot_status":
                    "STOPPED",

                "timestamp":
                    timestamp,

                "message":
                    "Device successfully recovered"
            }


        # -------------------------------------------------
        # RECOVERY FAILED
        # -------------------------------------------------

        print(
            "\n[!] SELF-HEALING FAILED"
        )

        print(
            "[!] Device remains protected."
        )


        self.response_logger.log_response(

            source_ip=source_ip,

            action="RECOVER",

            status="FAILED",

            trust_score=trust_score,

            behavior_risk=behavior_risk,

            reason=reason,

            message=(
                "Complete recovery verification failed"
            )
        )


        return {

            "source_ip":
                source_ip,

            "action":
                "RECOVER",

            "status":
                "FAILED",

            "trust_score":
                trust_score,

            "behavior_risk":
                behavior_risk,

            "timestamp":
                timestamp,

            "message":
                "Recovery verification failed"
        }


# =========================================================
# TEST
# =========================================================

def run_tests():

    manager = (
        SelfHealingManager()
    )


    test_ip = (
        "192.0.2.40"
    )


    print(
        "\n"
        + "=" * 60
    )

    print(
        "          AUTOMATIC THREAT CLEARANCE TEST"
    )

    print(
        "=" * 60
    )


    # -----------------------------------------------------
    # SHOW CURRENT STATE
    # -----------------------------------------------------

    print(
        "\n[1] Current protection state:"
    )


    print(
        "Isolated       :",
        manager.isolation_manager.is_isolated(
            test_ip
        )
    )


    print(
        "Traffic Blocked:",
        manager.traffic_isolation.is_blocked(
            test_ip
        )
    )


    print(
        "Honeypot Active:",
        manager.honeypot_manager.is_deployed(
            test_ip
        )
    )


    # -----------------------------------------------------
    # CHECK THREAT
    # -----------------------------------------------------

    print(
        "\n[2] Checking recent activity..."
    )


    clearance = (
        manager.check_threat_clearance(
            source_ip=test_ip,

            trust_score=90,

            behavior_risk=10,

            monitoring_minutes=5
        )
    )


    print(
        clearance
    )


    # -----------------------------------------------------
    # ATTEMPT RECOVERY
    # -----------------------------------------------------

    print(
        "\n[3] Attempting automatic recovery..."
    )


    result = (
        manager.recover_device(

            source_ip=test_ip,

            trust_score=90,

            behavior_risk=10,

            reason=(
                "No recent malicious activity "
                "and device behavior normalized"
            )
        )
    )


    print(
        "\nRecovery Result:"
    )

    print(
        result
    )


    # -----------------------------------------------------
    # FINAL STATE
    # -----------------------------------------------------

    print(
        "\n[4] Final device state:"
    )


    print(
        "Isolated       :",
        manager.isolation_manager.is_isolated(
            test_ip
        )
    )


    print(
        "Traffic Blocked:",
        manager.traffic_isolation.is_blocked(
            test_ip
        )
    )


    print(
        "Honeypot Active:",
        manager.honeypot_manager.is_deployed(
            test_ip
        )
    )


    print(
        "\n"
        + "=" * 60
    )

    print(
        "       AUTOMATIC THREAT CLEARANCE TEST COMPLETED"
    )

    print(
        "=" * 60
    )


# =========================================================
# MAIN
# =========================================================

if __name__ == "__main__":

    try:

        run_tests()

    except Exception as error:

        print(
            "\nERROR:"
        )

        print(
            error
        )